### ISSUE TITLE
Error of java.lang.NullPointerException - Test on a Server and Minecraft Launcher.

### ISSUE THREAD

**Issue by XxCoolGamesxX** [skyboy/MineFactoryReloaded#351]
Error:
Test on a Server and Minecraft Launcher.

Versions:
Forge Mod Loader version 7.10.85.1236 for Minecraft 1.7.10,
CoFHCore-[1.7.10]3.0.0B9-40,
MineFactoryReloaded-[1.7.10]2.8.0RC6-5.

Error Logs:
```
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.base.TileEntityFactory
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.machine.TileEntityEjector
[19:21:11] [Server thread/WARN] [MineFactoryReloaded/MineFactoryReloaded]: catching
java.lang.NullPointerException
	at cofh.mod.BaseMod.loadLang(BaseMod.java:188) [BaseMod.class:?]
	at powercrystals.minefactoryreloaded.MineFactoryReloadedCore.preInit(MineFactoryReloadedCore.java:280) [MineFactoryReloadedCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) [FMLModContainer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513) [Loader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88) [FMLServerHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319) [FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.transport.TileEntityConveyor
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetEnergy
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Stripping methods and fields from powercrystals.minefactoryreloaded.tile.rednet.TileEntityRedNetHistorian
[19:21:11] [Server thread/INFO] [CoFH ASM/MineFactoryReloaded]: Adding runtime interfaces to powercrystals.minefactoryreloaded.item.tool.ItemFactoryHammer
```
Need more info ask me. :D

**Comment by skyboy** [comment]
No longer an issue
