### ISSUE TITLE
2.8.0RC6-27 Unifier crash

### ISSUE THREAD

**Issue by liinux** [skyboy/MineFactoryReloaded#373]
Clicking on any part of the grid GUI of the Unifier produces a server crash.

The server uses the Tekkify modpack: http://www.technicpack.net/modpack/tekkify.2607/mods

```
[10:22:23] [Server thread/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[Messa
geToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageT
oMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:3
37) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323
) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultCh
annelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.c
lass:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxy
Packet.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:
?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:
?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
        at powercrystals.minefactoryreloaded.net.ServerPacketHandler.readData(ServerPacketHandler.java:248) ~[
ServerPacketHandler.class:?]
        at powercrystals.minefactoryreloaded.net.ServerPacketHandler.access$000(ServerPacketHandler.java:41) ~
[ServerPacketHandler.class:?]
        at powercrystals.minefactoryreloaded.net.ServerPacketHandler$MFRMessage.fromBytes(ServerPacketHandler.
java:317) ~[ServerPacketHandler$MFRMessage.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:17) ~[
SimpleIndexedCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.decodeInto(SimpleIndexedCodec.java:7) ~[S
impleIndexedCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.
java:77) ~[FMLIndexedMessageToMessageCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.
java:17) ~[FMLIndexedMessageToMessageCodec.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMes
sageCodec$2.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[Messa
geToMessageDecoder.class:?]
        ... 13 more
[10:22:23] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[Messa
geToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageT
oMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:3
37) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323
) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultCh
annelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.c
lass:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxy
Packet.class:git-Cauldron-MCPC-Plus-1.7.10-1.1286.06.217]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
```

**Comment by skyboy** [comment]
This appears to be an issue with cauldron.
