### ISSUE TITLE
compatibility Harvester/Planter/Fruit Picker

### ISSUE THREAD

**Issue by Tsunayoshi** [skyboy/MineFactoryReloaded#421]
Hello,

I am having issues with the current version of mfr.
Planter and Harvester are not abe to plant or harvest spalings from forestry, pam's harvestcraft, natura and bop.

The fruit picker also can't harvest apples from a apple sapling/tree by pam's harvestcraft.

I know that this all works in on the ftb map skyblocks (1) but also I know that this mod was hand over to the cofhteam and there where many changes in the cofhcore/rf energy system. So I won't complain, but I hope that in a future version the compatibility is implementet again.

Is there any plan for this and more important to me, in 1.7.10?

my mod versions:
forge-1.7.10-10.13.2.1352
CoFHCore-[1.7.10]3.0.0RC7-236
CoFHLib-[1.7.10]1.0.0RC7-140
MineFactoryReloaded-[1.7.10]2.8.0RC8-102

forestry_1.7.10-3.6.0.520-unstable
natura-1.7.10-2.2.0.1
BiomesOPlenty-1.7.10-2.1.0.1189-universal
Pam's HarvestCraft 1.7.10g

edit: Thaumcraft Greatwood working fine, silverwood not

**Comment by Tsunayoshi** [comment]
I have seen massiv errors from mfr to pam's harvest craft on server startup. It seems to me that mfr try to register the compatibly but throws acceptions:
[22:34:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchMethodException: cpw.mods.fml.common.event.FMLInterModComms$IMCMessage.<init>(java.lang.String, java.lang.Object)
[22:34:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Class.getConstructor0(Class.java:3082)
[22:34:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.Class.getConstructor(Class.java:1825)
[22:34:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at powercrystals.minefactoryreloaded.api.FactoryRegistry.sendMessage(FactoryRegistry.java:101)
[22:34:29] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.pam.harvestcraft.PamMFRCompatibility.getRegistry(PamMFRCompatibility.java:178)

It was to fast to get I all and full. Hope this helps!!

**Comment by skyboy** [comment]
I have no idea what mod causes this error, but something is fundamentally breaking a forge feature. I can't do anything about it.
