### ISSUE TITLE
Crash on Server, Harvester related

### ISSUE THREAD

**Issue by TiranDirth** [skyboy/MineFactoryReloaded#437]
Running a server, so unfortunately did not see the exact set of actions that caused this.
The user in question claims the last thing they did is place a plastic tank, if the chunk is loaded for any reason, it crashes with the following crashlog:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 22/04/15 13:44
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:388)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:326)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:322)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:277)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:219)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryInventory.doDrop(TileEntityFactoryInventory.java:255)
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester.activateMachine(TileEntityHarvester.java:199)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:109)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:388)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:326)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStackInAir(UtilInventory.java:322)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:277)
	at powercrystals.minefactoryreloaded.core.UtilInventory.dropStack(UtilInventory.java:219)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryInventory.doDrop(TileEntityFactoryInventory.java:255)
	at powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester.activateMachine(TileEntityHarvester.java:199)
	at powercrystals.minefactoryreloaded.tile.base.TileEntityFactoryPowered.func_145845_h(TileEntityFactoryPowered.java:109)

-- Block entity being ticked --
Details:
	Name: factoryHarvester // powercrystals.minefactoryreloaded.tile.machine.TileEntityHarvester
	Block type: ID #663 (tile.mfr.machine.0 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (342,12,988), Chunk: (at 6,0,12 in 21,61; contains blocks 336,0,976 to 351,255,991), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #663 (tile.mfr.machine.0 // powercrystals.minefactoryreloaded.block.BlockFactoryMachine)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: maz_is_short
	All players: 1 total; [GCEntityPlayerMP['TiranDirth'/614, l='maz_is_short', x=512.98, y=181.58, z=1073.81]]
	Chunk stats: ServerChunkCache: 668 Drop: 0
	Level seed: 4456808546156290676
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (535,192,1030), Chunk: (at 7,12,6 in 33,64; contains blocks 528,0,1024 to 543,255,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Level time: 264429902 game time, 163818373 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 65394 (now: false), thunder time: 52603 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 2.6.32-358.23.2.el6.x86_64
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 403967816 bytes (385 MB) / 961019904 bytes (916 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2048M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 93
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 67 mods loaded, 67 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (ForgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (ForgeMod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{7.0.1} [BuildCraft] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{7.0.1} [BC Silicon] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{7.0.1} [BC Transport] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{7.0.1} [BC Builders] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Robotics{7.0.1} [BC Robotics] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{7.0.1} [BC Energy] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{7.0.1} [BC Factory] (buildcraft-7.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CarpentersBlocks{3.3.0.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.0.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.320.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.320.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	HardcoreEnderExpansion{1.8} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.41.729} [Iron Chest] (ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ModTweaker{0.6} [ModTweaker] (ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	simplyjetpacks{1.3.0} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TabulaRasa{1.7.10R1.0.1} [Tabula Rasa] (TabulaRasa-[1.7.10]1.0.1-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	CoFHCore: -[1.7.10]3.0.2-262
	ThermalFoundation: -[1.7.10]1.0.0-81
	ThermalExpansion: -[1.7.10]4.0.1-182
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0-80
	ThermalDynamics: -[1.7.10]1.0.0-122
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [GCEntityPlayerMP['TiranDirth'/614, l='maz_is_short', x=512.98, y=181.58, z=1073.81]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Since the error I have updated MFR (and all COFH mods) in an effort to fix the problem, but to no avail, this crashlog is after updating.

**Comment by TiranDirth** [comment]
Going in with MCEdit, seems as I delete a harvester the same error is coming up on every harvester in the world one at a time.
Deleting all powered harvesters has stopped it crashing.

**Comment by TiranDirth** [comment]
Further testing: the harvesters causing the crashes were connected by buildcraft pipes, trying to take items from the bottom and also had no/not enough sludge handling. Other harvesters where items were pulled from the back (both Buildcraft and Thermal Dynamics pipes) and sludge was handled well are working fine.
