### ISSUE TITLE
Weird "crash" on world generation w/ Thaumcraft

### ISSUE THREAD

**Issue by T145** [skyboy/MineFactoryReloaded#450]
```
[23:33:07] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[23:33:07] [Server thread/WARN] [FML]: =============================================================
[23:33:07] [Server thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[23:33:07] [Server thread/WARN] [FML]: Offendor: org/multimc/EntryPoint.main([Ljava/lang/String;)V
[23:33:07] [Server thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[23:33:07] [Server thread/WARN] [FML]: =============================================================
[23:33:07] [Server thread/ERROR] [FML]: Caught exception from MineFactoryReloaded|CompatThaumcraft
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor167.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_45]
	at cofh.api.modhelpers.ThaumcraftHelper.parseAspects(ThaumcraftHelper.java:116) ~[ThaumcraftHelper.class:?]
	at powercrystals.minefactoryreloaded.modhelpers.thaumcraft.Thaumcraft.parseAspects2(Thaumcraft.java:250) ~[Thaumcraft.class:?]
	at powercrystals.minefactoryreloaded.modhelpers.thaumcraft.Thaumcraft.doAspects(Thaumcraft.java:274) ~[Thaumcraft.class:?]
	at powercrystals.minefactoryreloaded.modhelpers.thaumcraft.Thaumcraft.load(Thaumcraft.java:245) ~[Thaumcraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.3.1400-1.7.10-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:720) ~[Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:309) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) ~[1.7.10.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.11.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) ~[OneSixLauncher.class:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) ~[OneSixLauncher.class:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) ~[EntryPoint.class:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) ~[EntryPoint.class:?]
Caused by: java.lang.StackOverflowError
	at thaumcraft.api.aspects.AspectList.getAspects(AspectList.java:65) ~[AspectList.class:?]
	at thaumcraft.api.aspects.AspectList.copy(AspectList.java:35) ~[AspectList.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:567) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]

etc.

thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
[23:33:07] [Server thread/INFO] [FML]: Applying holder lookups
[23:33:07] [Server thread/WARN] [FML]: Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?
[23:33:07] [Server thread/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[23:33:07] [Server thread/WARN] [FML]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[23:33:07] [Server thread/INFO] [FML]: Holder lookups applied
[23:33:07] [Server thread/INFO] [Compact Machines]: Unregistering dimension -3 on client side
[23:33:07] [pool-7-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data 
[23:33:07] [Server thread/INFO] [STDOUT]: [mcjty.rftools.RFTools:serverStopped:207]: ###### RFTools.serverStopped
[23:33:07] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[23:33:07] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[23:34:12] [Client thread/INFO] [LiteLoader]: LiteLoader is shutting down, shutting down core providers and syncing configuration
[23:34:12] [Client thread/INFO] [LiteLoader]: Baking listener list for ShutdownObserver with 2 listeners
[23:34:12] [Client thread/INFO]: Stopping!
[23:34:12] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[23:34:12] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[23:34:13] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[23:34:13] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
Game exited with exitcode 1.
```
Would this be considered a problem w/ MFR?

**Comment by Sky5urf** [comment]
Same crash, on world load, or world gen.

**Comment by Beelzaboss** [comment]
Same...

**Comment by epilimic** [comment]
Same here. Once I removed MFR it generated right away. Tried a few different versions prior to removing it but nothing would work.

**Comment by T145** [comment]
After removing Witching Gadgets and Traveller's Gear the crash resolved itself for me, so perhaps the problem is w/ one of those mods?

**Comment by Beelzaboss** [comment]
I just removed the loading of Thaumcraft support and the modhelper inside MFR for now.

I also think it may be Witching Gadgets, my pack have it also installed.

**Comment by alfw** [comment]
@T145 @epilimic @Sky5urf @Beelzaboss I poked mod creator of WitchingGadtgets about it, open the WitchingGadtgets's config and change "enable transmutations" to false @T145 @epilimic

**Comment by Sky5urf** [comment]
In my instance of RR3, there isn't Witching Gadgets. Might be Magical Crops Beta 3.0 (updated version of what is in the pack), as i've read on others threads regarding this issue

**Comment by skyboy** [comment]
Yeah, this is caused by other mods creating aspect loops. It's out of my control, and something that should be detected by thaumcraft but is not.
