### ISSUE TITLE
Client crashing on server

### ISSUE THREAD

**Issue by Nerokinkage** [skyboy/MineFactoryReloaded#488]
Hello, I know this is a duplication of another. I read skyboy/MineFactoryReloaded#266 and have read that it could be a possibility of a corrupted world, but I don't think this is the case. Just like #266 but I use Optifine to help render some things and to increase my FPS since this modpack has some of the big mods. I had this error before a few weeks back on a server that I play on with a few of my friends. Since those past weeks, I haven't gotten this error once. But now, my friends have been experiencing this error and I haven't these few weeks. The error I have pasted below came from an old crash log I had. I uploaded the complete log to [Pastebin](http://pastebin.com/XH7gBpuh) just in case.  

```
java.lang.ArrayIndexOutOfBoundsException: 2
	at powercrystals.minefactoryreloaded.block.BlockRubberLeaves.func_149691_a(BlockRubberLeaves.java:65)
	at powercrystals.minefactoryreloaded.block.BlockRubberLeaves.func_149673_e(BlockRubberLeaves.java:58)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:9361)
	at net.minecraft.client.renderer.RenderBlocks.func_147736_d(RenderBlocks.java:6562)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4716)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:307)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:320)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2245)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1513)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1304)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by skyboy** [comment]
If it is optifine, then it should not be altering mod's block data. Disable *everything* related to 'enhancing' vanilla like connected textures and see if it persists.

**Comment by Nerokinkage** [comment]
Here's the settings I currently have set to Optifine: [Pastebin](http://pastebin.com/MQMGMxzd)

**Comment by Nerokinkage** [comment]
Well... After countless days after removing the mod, opening the server, shutting it down and adding it back stopped the crash... Quite strange...
