### ISSUE TITLE
Crash when generating a new world after installing MFR

### ISSUE THREAD

**Issue by az201601** [skyboy/MineFactoryReloaded#582]
http://pastebin.com/Wn9ug2ER

**Comment by skyboy** [comment]
This is most likely related to this https://github.com/skyboy/MineFactoryReloaded/commit/25fd5f866bbd0dd72134004e054ca245e066cc62

**Comment by skyboy** [comment]
Wrong issue when moving through tabs

**Comment by skyboy** [comment]
```
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
    at ru.fewizz.idextender.asm.IETransformer.transform(IETransformer.java:52)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 17 more
Caused by: java.lang.NullPointerException
    at ru.fewizz.idextender.asm.transformer.CofhBlockHelper.transform(CofhBlockHelper.java:18)
    at ru.fewizz.idextender.asm.IETransformer.transform(IETransformer.java:46)
    ... 19 more
```

Your problem is this mod.
