### ISSUE TITLE
Crash when placing Grindr on SpongeForge server

### ISSUE THREAD

**Issue by kaal-1** [skyboy/MineFactoryReloaded#657]
Minecraft 1.10.2
Forge 2281
Latest SpongeForge

When I place the Grinder on the ground the server crashes:
https://hastebin.com/avirelagiy.http

**Comment by essem2** [comment]
same with nearly every block

**Comment by P3pp3rF1y** [comment]
@kaal-1 what version of cofhcore you have there?

@essem2 I really doubt that is the case as only grinder and slaughterhouse use worldserverproxy, so either you're getting a different issue or you're fine.

**Comment by essem2** [comment]
@P3pp3rF1y got it with slaughterhouse but heared from some players that other blocks crashes too

**Comment by kaal-1** [comment]
CoFHCore-1.10.2-4.1.11.16-universal

**Comment by EZKatnipz** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1708

**Comment by EZKatnipz** [comment]
While testing the different machines, seems like the AutoAnvil also causes the crash. At least that was the last machine placed before the server (and the client) crashed.

**Comment by EZKatnipz** [comment]
nah, Auto Anvil is fine, just the Block Breaker, Block Smasher, Grinder, and Slaughterhouse.
[crash-2017-08-10_06.41.29-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1219552/crash-2017-08-10_06.41.29-server.txt)

**Comment by mkrtes** [comment]
I have same problem

**Comment by mminkus** [comment]
I have a crash with the grinder.

`
Time: 8/17/17 3:58 AM
Description: Ticking entity

java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    cofh/asmhooks/world/WorldServerProxy.func_72970_h()Lnet/minecraft/world/chunk/IChunkProvider; @4: invokevirtual
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'cofh/asmhooks/world/WorldServerProxy' }
    stack: { 'net/minecraft/world/WorldServer' }
  Bytecode:
    0x0000000: 2ab4 003a b603 69b0

        at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.func_145834_a(TileEntityGrinder.java:79)
        at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:809)
        at net.minecraft.world.World.func_175690_a(World.java:2461)
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
        at net.minecraft.world.World.func_175625_s(World.java:2402)
        at powercrystals.minefactoryreloaded.block.BlockFactory.collisionRayTrace(BlockFactory.java:333)
        at powercrystals.minefactoryreloaded.block.BlockFactory.func_180636_a(BlockFactory.java:324)
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185910_a(BlockStateContainer.java:448)
        at net.minecraft.world.World.func_147447_a(World.java:1018)`

**Comment by kaal-1** [comment]
It was fixed on sponge side https://github.com/SpongePowered/SpongeCommon/commit/37f61741d354ce059ffaaf951574b73041a08dd4
